### PR TITLE
Convert from govendor to glide

### PR DESCRIPTION
**Pull request by msabramo**
Cc: @iderdik. @f4tq

### CODE REVIEW

**Comment by iderdik** [comment]
👍

**Comment by msabramo** [comment]
I don't have the ability to merge on this repo

**Comment by iderdik** [comment]
@f4tq, as maintainer, can you do the honors please?

**Comment by msabramo** [comment]
Closing because I talked to @f4tq and he said `govendor` is pretty integral to the build process.

I asked him to simply change the govendor deps to loosely pin for negroni, ginkgo, and gomega.

That should fix these warnings I believe that glide emits when updating deps for Flight Director:

```
[WARN]	Conflict: github.com/codegangsta/negroni version is ~0.2.0, but also asked for 8d75e11374a1928608c906fe745b538483e7aeb2
[WARN]	Conflict: github.com/onsi/ginkgo version is ~1.3.1, but also asked for 38caab951a9ff39f0e61294a1dbaaa074a39228b
[WARN]	Conflict: github.com/onsi/gomega version is ~1.1.0, but also asked for 8adf9e1730c55cdc590de7d49766cb2acc88d8f2
```

**Pull request closed without merging**
